CREATE SEQUENCE  "EZ_CONSUMER"."S_TOOLBAR2"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  "EZ_CONSUMER"."S_TOOLBAR2_RULE"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;

  CREATE TABLE "EZ_CONSUMER"."EZTOOLBAR2" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PRIORITY" NUMBER(*,0), 
	"TOOLNAME" VARCHAR2(4000), 
	"TOOLBARNAME" VARCHAR2(4000), 
	"SITEACCESS" VARCHAR2(4000)
   ) ;
  ALTER TABLE "EZ_CONSUMER"."EZTOOLBAR2" ADD CONSTRAINT "EZTOOLBAR2_PK" PRIMARY KEY ("ID") ENABLE;
 

  CREATE OR REPLACE TRIGGER "EZ_CONSUMER"."EZTOOLBAR2_ID_TR" 
BEFORE INSERT ON eztoolbar2 FOR EACH ROW    WHEN (new.id IS NULL) BEGIN
  SELECT s_toolbar2.nextval INTO :new.id FROM dual;
END;
/
ALTER TRIGGER "EZ_CONSUMER"."EZTOOLBAR2_ID_TR" ENABLE;
 

  CREATE TABLE "EZ_CONSUMER"."EZTOOLBAR2_RULE" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PRIORITY" NUMBER(*,0), 
	"TYPE" NUMBER(*,0), 
	"NODE_ID" NUMBER(*,0), 
	"INCLUDE" NUMBER(*,0), 
	"TOOLBAR_ID" NUMBER(*,0)
   ) ;
  ALTER TABLE "EZ_CONSUMER"."EZTOOLBAR2_RULE" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID") ENABLE;
 

  CREATE OR REPLACE TRIGGER "EZ_CONSUMER"."EZTOOLBAR2_RULE_ID_TR" 
BEFORE INSERT ON eztoolbar2_rule FOR EACH ROW    WHEN (new.id IS NULL) BEGIN
  SELECT s_toolbar2_rule.nextval INTO :new.id FROM dual;
END;
/
ALTER TRIGGER "EZ_CONSUMER"."EZTOOLBAR2_RULE_ID_TR" ENABLE;
 

  CREATE OR REPLACE TRIGGER "EZ_CONSUMER"."EZTOOLBAR2_ID_TR" 
BEFORE INSERT ON eztoolbar2 FOR EACH ROW    WHEN (new.id IS NULL) BEGIN
  SELECT s_toolbar2.nextval INTO :new.id FROM dual;
END;
/
ALTER TRIGGER "EZ_CONSUMER"."EZTOOLBAR2_ID_TR" ENABLE;
 

  CREATE OR REPLACE TRIGGER "EZ_CONSUMER"."EZTOOLBAR2_RULE_ID_TR" 
BEFORE INSERT ON eztoolbar2_rule FOR EACH ROW    WHEN (new.id IS NULL) BEGIN
  SELECT s_toolbar2_rule.nextval INTO :new.id FROM dual;
END;
/
ALTER TRIGGER "EZ_CONSUMER"."EZTOOLBAR2_RULE_ID_TR" ENABLE;